### ISSUE TITLE
Webmentions for Multi Language

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#111]
An issue was raised by HWC Brussels over the fact they have two different versions of a page (English/French) and want the mentions to show on both.

Opening this to explore possibilities.

**Comment by NCols** [comment]
We use qTranslate on hwc.brussels.
I created a post in order to create a new event: 
EN: https://hwc.brussels/event-test-3/
FR: https://hwc.brussels/fr/event-test-3/

When I rsvp with my domain (ncollig.net) on the /fr/ url, nothing seems to happen. But when I rsvp on the main post, https://hwc.brussels/event-test-3/, the webmention works, the rsvp is added in the comments, and it also displays the rsvp/comment on the French page.

So the main problem is that the /fr/ page doesn't receive the rsvp.

**Comment by dshanske** [comment]
The simple question is how do you say page x is an alias of page y in another language?

**Comment by pfefferle** [comment]
We use `url_to_postid` to map the target URL to a Post-ID. I did a little research on qTranslate and the do not hook up the `url_to_postid`, that's why we can't find a valid post. I think the best solution is to ask the qTranslate team to add `url_to_postid` support.
