### ISSUE TITLE
Akismet marking webmentions as spam

### ISSUE THREAD

**Issue by armingrewe** [pfefferle/wordpress-webmention#158]
Before I raise it with Akismet just wanted to check if anyone else has the same problem:
I had a similar problem a few years ago, but after a while it stopped. Now it's started again: for a few days now Akismet marks some of my webmentions (from all three "sources", Twitter, FB, G+) as spam.
Anyone else see the same?

**Comment by chrisaldrich** [comment]
I know that @dshanske  was communicating with Akismet a year or so ago and they were taking in examples at the time to fix the issue, but I haven't seen any recent updates about where that stands. I don't recall offhand where that issue was being tracked/don't see it now.

There was also some discussion in #87 as you'll recall. 

In the erstwhile, there's some code you can use to prevent Akismet from marking them as spam in the first place: https://indieweb.org/WordPress_with_Bridgy#Spam

**Comment by armingrewe** [comment]
Been monitoring this for the last few weeks, it seems to have sorted itself out again, I had hardly any false positives over the last two weeks. I'll close this for now. Fingers crossed it all stays good.
