### ISSUE TITLE
updating comment blows away semantic linkbank information

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-webmention#57]
When a webmention dupe/update comes in, all semantic linkback content is lost if using https://github.com/pfefferle/wordpress-semantic-linkbacks

**Comment by pfefferle** [comment]
This is strange, because I tested it several times with the [webmention test pinger](https://github.com/voxpelli/node-webmention-testpinger) of @voxpelli

Will run some more tests with the latest version of the plugins.

**Comment by dshanske** [comment]
This is partly because of my changes to have linkback_fix in Semantic Linkbacks run on 'comment_post' as opposed to 'webmention_post'

But webmention_post does not behave like comment_post or pingback_post...as those are only fired on new comments. Would suggest that we change the behavior here to reflect this and add another hook, webmention_update, only triggered on an update.

**Comment by pfefferle** [comment]
I think this is fixed now
